### PR TITLE
chore: replace vulnerable dependencies for imageHotspotCreator

### PR DESCRIPTION
**Pull request by t-col**
Removes dependencies on unmaintained react-scripts and emotion packages. Replaces `react-scripts` with `vite`/`vitest`. Replaces `emotion` with `@emotion/css`. Also removes an unused dependency on the unmaintained `@contentful/forma-36-react-components` package.

### CODE REVIEW

**Comment by whitelisab** [comment]
@vijayaragavan462 tagging you on this PR since we were chatting on another PR 😄 

Can you please review this PR and let us know if we are ok to merge this? Thank you!

**Comment by vijayaragavan462** [comment]
> @vijayaragavan462 tagging you on this PR since we were chatting on another PR 😄
> 
> Can you please review this PR and let us know if we are ok to merge this? Thank you!

Hi team, apologies for the late reply. Yeah, I have verified this PR, and everything looks okay to be merged.

**Comment by jjolton-contentful** [comment]
> Hi team, apologies for the late reply. Yeah, I have verified this PR. There were some issues, I think.As I can see, GetAssets was deprecated from SDK.

Hey @vijayaragavan462 thank you for verifying! You are totally right that the `sdk.space` method is deprecated, I've gone ahead and swapped that out for `sdk.cma.asset` in both places where it was used, and added some types for you to help with future development. 

I'll leave this PR up for another few days before merging to give you a chance to sign off on these latest changes if you have a moment.

**Comment by vijayaragavan462** [comment]
> > Hi team, apologies for the late reply. Yeah, I have verified this PR. There were some issues, I think.As I can see, GetAssets was deprecated from SDK.
> 
> Hey @vijayaragavan462 thank you for verifying! You are totally right that the `sdk.space` method is deprecated, I've gone ahead and swapped that out for `sdk.cma.asset` in both places where it was used, and added some types for you to help with future development.
> 
> I'll leave this PR up for another few days before merging to give you a chance to sign off on these latest changes if you have a moment.

Hi @jjolton-contentful , Yeah, it seems to be okay now.It was **Looks Good To Merge (LGTM)**.

**Comment by vijayaragavan462** [comment]
Hi @jjolton-contentful  ,

I noticed this PR hasn’t been merged for some time. Do you have any updates on its status? I also see there are other PRs pending after this one.

Thank you!

**Review by mgoudy91 — APPROVED** [review]

**Pull request merged**
