### PR TITLE
fix: Transifex app handle deleted project case

### PR DESCRIPTION
**Pull request by foteinigk**
## Purpose

Improve the error we get on configuration page when transifex project is deleted and app's installation has not been completed yet.

## Approach

Display a relevant error message and allow users to reset selected project

## Testing steps

- Install transisfex native app and connect it with a transifex project without completing the installation
- Delete transifex project
- On refresh user should see the following view

Screenshot 2024-04-30 at 12 11 18 PM

### CODE REVIEW

**Comment by foteinigk** [comment]
Hi  @lilbitner 🙂! Not sure who I should ping, could you check this PR at your convenience? We have already tested it internally, Thanks a lot in advance🙏

**Comment by jsdalton** [comment]
Thanks for the ping @foteinigk. This is good to go. Merge when ready and we will deploy the change in the next release (this week).

**Comment by foteinigk** [comment]
> Thanks for the ping @foteinigk. This is good to go. Merge when ready and we will deploy the change in the next release (this week).

Thanks a lot @jsdalton ! Just a note, I can't see the merge option, maybe it has to do with my permissions on this repo.

**Comment by mkiousi** [comment]
Hello from Transifex! Is there an ETA on when the second reviewer from Contentful team will review this PR?

**Comment by lilbitner** [comment]
@foteinigk There seem to exist merge conflicts within this branch now, perhaps after merging the other open PR. Do you mind resolving these conflicts, and then we will go ahead and merge it 😃

**Pull request merged**
