### PR TITLE
fix: Updating the protocol of image url

### PR DESCRIPTION
**Pull request by vijayaragavan462**
# Purpose

We need to ensure that all image URLs use the https:// protocol instead of http://. The http protocol is not supported in some environments, whereas https is universally accepted and provides enhanced security through encryption. Using https:// ensures compatibility across all platforms and improves the security of data transmission.

### CODE REVIEW

**Comment by vijayaragavan462** [comment]
Hi Team,

Our users have reported an issue related to this minor change. It would be appreciated if this pull request could be reviewed and merged at your earliest convenience.

Thank you.

**Review by mgoudy91 — APPROVED** [review]

**Comment by mgoudy91** [comment]
thanks @vijayaragavan462 I'll get this merged and deployed now

**Comment by vijayaragavan462** [comment]
Hi, @mgoudy91  Thanks for merging.

Does it take time to be updated in the application?

**Comment by mgoudy91** [comment]
@vijayaragavan462 I just set a deploy to start momentarily, should be out in the next 15 minutes or so

**Comment by vijayaragavan462** [comment]
> @vijayaragavan462 I just set a deploy to start momentarily, should be out in the next 15 minutes or so

Thanks @mgoudy91

**Pull request merged**
