### PR TITLE
feat: Intershop - Contentful

### PR DESCRIPTION
**Pull request by two-point-o**
## Purpose

The Contentful Marketplace now features a practical standalone application that connects Contentful with Intershop. This tool allows users to conveniently browse through the Intershop catalogue and incorporate selected products into their Contentful content, using SKU IDs for product representation.

## Approach

We build it using Intershop API, with upfront configuration and mapping to connect you can easily connect app to field.

### First install

1. Install the application.
2. Configure your intershop API
3. Map fields on Intershop attributes
4. Connect app as Json field

## Breaking Changes

First submission.

## Dependencies and/or References

In the README file.

### CODE REVIEW

**Review by whitelisab — COMMENTED** [review]
Thanks for opening this PR! I have added just a few comments here. Let me know if you have any questions.

**Comment by whitelisab** [comment]
@two-point-o Can you confirm a few things that will ensure that we get your marketplace app definition set up properly?

- Can you confirm that the app uses only the App Configuration and Entry Field locations? For the Entry Field location, what are the field types that the app can be rendered in?
- I noticed that you are using instance parameters in your app. Can you please share with us how these should be configured?

Feel free to reply here or with our team via email. Thanks!

**Comment by two-point-o** [comment]
@whitelisab thank you for the response!

As you mentioned the app only uses the `App Configuration` and `Entry Field` locations. We also use the `Dialog` location within our code, I'm not sure whether this is relevant for your question?
Only the `JSON object` field type will be used for the entry field location.
Below image contains a screenshot of our development app definition with the previously mentioned locations and field type being toggled.

image

I've also looked into your comment about the instance parameters. It seems that those values aren't being utilized at the moment and are technical debt that we've forgotten to remove.

We'll start making your requested changes (update year in license and update id in package.json) now and remove the legacy instance parameters.

Once the changes have been made we'll add another comment.

**Comment by two-point-o** [comment]
@whitelisab all the changes you requested have been made. All references of the instance parameters have also been removed. 

Please let us know if there's still something we've got to provide/do.

**Review by whitelisab — COMMENTED** [review]
@two-point-o thank you for addressing these changes! Can you just fix the merge conflict in the `release-please-config.json` file and then I'll approve and merge this in. Thank you!

**Comment by two-point-o** [comment]
@whitelisab the merge conflict has been resolved. 

We're looking forward to the approval and merge. 

Thanks for your help throughout the review

**Review by whitelisab — APPROVED** [review]
Thank you for making the requested changes, this looks good!

**Pull request merged**
