### PR TITLE
chore: replace vulnerable dependencies for voucherify

### PR DESCRIPTION
**Pull request by t-col**
Removes dependency on unmaintained react-scripts package, replaces it with `vite`/`vitest`

### CODE REVIEW

**Comment by weronika-kurczyna** [comment]
Hi @t-col 
Thank you for the information. Of course, we'll check the app for any bugs or issues and let you know in this PR.

**Comment by weronika-kurczyna** [comment]
LGTM

**Comment by t-col** [comment]
thank you for your prompt reply @weronika-kurczyna !

**Review by david-shibley-contentful — APPROVED** [review]
LGTM

**Pull request merged**
