### PR TITLE
feat: Xillio Transcreate App

### PR DESCRIPTION
**Pull request by ghuisma**
Hi all!

This is the source code for the HelloTranslate app.

We currently have a monorepo setup with a shared package containing Zod schemas and the corresponding TypeScript types inferred from those, which we're using in both our backend and frontend. Well, it turns out this doesn't work very well with your MPA repo/setup. :facepalm: 

For now, I manually included the shared type declarations in `/types`. I'll work out a more elegant solution for that in the future. Quite possibly this would involve publishing the type declarations on NPM. But we might also come up with a different solution. Anyway, that's very much an "us" problem and not a "you" problem. We'll figure something out. :muscle: 

If there's anything in this PR that's missing or not up to standard, please let me know, and I will fix it ASAP. 

Thanks! :heart:

### CODE REVIEW

**Comment by matthew-gordon** [comment]
Hello @ghuisma! Thank you for opening this PR, there are just a couple of things that need to be addressed:

- Can you please add your app to the `release-please-config.json`
- A `LICENSE` file needs to be added

**Comment by mgoudy91** [comment]
@ghuisma Thanks again for submitting, this all is looking great and ready to merge. The only thing we need you to do is rebase/merge the pick up the most recent release please configuration.

Sorry to have to ask you to do this, I don't have the ability to make changes to your fork.

After that we should be ready to release!

**Comment by ghuisma** [comment]
@mgoudy91 No problem at all! Should be good to go now :smile:

**Review by mgoudy91 — APPROVED** [review]

**Comment by mgoudy91** [comment]
@ghuisma thanks, I'll get this merged and deployed

**Pull request merged**
