### PR TITLE
refactor: migrate Raster app from Next.js to Vite app to facilitate deployment

### PR DESCRIPTION
**Pull request by emwp**
## Purpose
There were issue deploying the Raster app to production due to it being a Next.js app – To make it easier we just migrated to a Vite app.

## Approach
Just migrated to a Vite app.

## Breaking Changes
No breaking changes

## Dependencies and/or References
https://github.com/contentful/marketplace-partner-apps/pull/2284 – PR with issue deploying the app.

### CODE REVIEW

**Comment by david-shibley-contentful** [comment]
@emwp I am testing the app locally. The app installs just fine but when fetching my libraries the result is always an empty array. Is there something I am doing wrong? I have ensured that I have libraries and my API key has read permissions on the libraries.

**Comment by emwp** [comment]
> @emwp I am testing the app locally. The app installs just fine but when fetching my libraries the result is always an empty array. Is there something I am doing wrong? I have ensured that I have libraries and my API key has read permissions on the libraries.

Hey! So one thing I think might not be sufficiently clear is that Organization ID when configuring the app, should be the Raster org id and not Contentful. Take a look at this image from the Raster Organization settings page:
image

From Contentful config page:

image


Please let me know if you're still not able to make it work, I'll try to set it up with a different org as well. If needed we can hop into a quick call.

**Comment by david-shibley-contentful** [comment]
@emwp Thank you for all that detail! I am indeed using the raster org id `f87fke3h23jcf2` and have the other steps completed as well. Here is my request object:
```
{"query":"\n  query Query($organizationId: String!) {\n    libraries(organizationId: $organizationId) {\n      id\n      name\n      photosCount\n    }\n  }\n","operationName":"Query","variables":{"organizationId":"f87fke3h23jcf2"}}
```

and here is the response:
```
{"data":{"libraries":[]}}
```

here is my raster:
Screenshot 2024-08-27 at 1 50 02 PM

here are my libraries:
Screenshot 2024-08-27 at 1 51 38 PM

**Comment by david-shibley-contentful** [comment]
@emwp I am open to jumping on a call too

**Comment by david-shibley-contentful** [comment]
Tried this again today, pulled the latest changes and it is working now!

**Comment by david-shibley-contentful** [comment]
Just need to resolve the merge conflicts and we can merge this 🚢

**Comment by emwp** [comment]
> Just need to resolve the merge conflicts and we can merge this 🚢

Hey @david-shibley-contentful should be good now!

**Review by david-shibley-contentful — APPROVED** [review]

**Pull request merged**
